version: "3"
services:
  web:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  tests:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: [ "npm", "run", "test" ]
